### ISSUE TITLE
入群二维码已失效，可以更新吗

### ISSUE THREAD

**Issue by dgo2dance** [liuzhao1225/YouDub-webui#2]
入群二维码已失效，可以更新吗

**Comment by 21iridescent** [comment]
+1

**Comment by MeYoung** [comment]
+1

**Comment by Polaris-F** [comment]
+1

**Comment by lifan-lifan** [comment]
又失效了

**Comment by hezeen** [comment]
可以再更新下码

**Comment by lindembergandrade** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
vidhanmangla, @rezarudy, @Maudykaz, @virtualsuccessdev, @MaryamRezazade, @topaccina, @ahoramazdaa, @apianta, @davhud, @RishiKeerthi, @sadityakumar9211, @linux2020, @lowk3v, @Spt117, @davishoang, @zdus4w, @liuzhao1225, @Cypher4300, @Elitsuv, @AmirNasrollahi, @henrimahal, @silaslenihan, @mdeyn, @KunalKaushik2, @kaznak, @hoangkimthu37, @imagineaizy, @MelikNabiOzcan, @cotoneum, @arunadaybasu, @eesilas, @leandroglopez, @ajays97, @OmarMWarraich, @chuanyue98, @mikolajroszak, @HatemSaadallah, @GoesToTwentyOne, @kryptokent, @mattbrc, @Xiaobo2020, @sharmavaibhav059, @kvngdavid, @SunJ3t, @Gopaloraon, @anupamdey2001, @Ajreality1, @baoanh1310, @XiaoNai1987, @simluyt

**Comment by MulatramAwA** [comment]
+1

**Comment by liuzhao1225** [comment]
> 建议直接用discord，希望作者赶快看issue，这个库感觉很不活跃

非常好建议，已采纳。
Join our Discord server for discussions and support: [Discord Server](https://discord.gg/UhxHxNCX2C)
